spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop


# ===============================
# JWT (dummy values for test)
# ===============================
jwt.secret=${JWT_SECRET:testsecretkey1234567890testsecretkey1234567890}
jwt.expiration=${JWT_EXPIRATION:3600000}

server.port=0

spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration,\
org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration