spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

server.port=0

# JWT dummy
jwt.secret=testsecretkey1234567890
jwt.expiration=3600000

# 🔥 disable ALL external चीजें
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration,\
org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,\
org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# dummy twilio
twilio.account.sid=dummy
twilio.auth.token=dummy
twilio.phone.number=dummy

# for razorpay
razorpay.key.id = test_key
razorpay.key.secret = test_secret
